#!/bin/bash
clear
echo -e "\e[1;33m*************************************************\e[0m"
echo -e "\e[1;33m*                                               *\e[0m"
echo -e "\e[1;33m*             LAZY NICKNAME GENERATOR           *\e[0m"
echo -e "\e[1;33m*                                               *\e[0m"
echo -e "\e[1;33m*************************************************\e[0m"
echo ""
# Define arrays of adjectives and nouns
adjectives=(
    "Chaos"
    "Necrotic"
    "Cosmic"
    "Grave"
    "Venomous"
    "Void"
    "Demonic"
    "Dark"
    "Astral"
    "Spectral"
    "Ethereal"
    "Mystic"
    "Eerie"
    "Frostbitten"
    "Infernal"
    "Cryptic"
    "Twisted"
    "Apocalyptic"
    "Ravenous"
    "Malevolent"
    "Occult"
    "Sinister"
    "Blasphemous"
    "Morbid"
    "Nocturnal"
    "Soulless"
    "Sanguine"
    "Sickening"
    "Thunderous"
    "Wretched"
    "Hacktastic"
"Hackerish"
"Cybernetic"
"Cryptic"
"Nefarious"
"Viral"
"Techno"
"Phreaky"
"Malicious"
"Stealthy"
"Cyberpunk"
"Darknet"
"Lethal"
"Cyberwarrior"
"Rogue"
"Shadowy"
"Untraceable"
"Deviant"
"Unholy"
"Blackhat"
"Underground"
"Unpredictable"
"Cyberassassin"
"Cyberterrorist"
"Anarchic"
"Cybercommando"
"Cybermercenary"
"Cyberrebel"
"Cybersoldier"
"Cyberstormtrooper"
"Kali"
"Ubuntu"
"Arch"
"Debian"
"Fedora"
"CentOS"
"Mint"
"RedHat"
"Gentoo"
"Slackware"
"SUSE"
"Lubuntu"
"Xubuntu"
"Manjaro"
"Void"
"Antergos"
"OpenSUSE"
"PCLinuxOS"
"Mageia"
"Zorin"
"Parrot"
"FreeBSD"
"OpenBSD"
"NetBSD"
"DragonFly"
"Alpine"
"Clear"
"Core"
"Endeavour"


)
nouns=(
    "Oni"
    "Shogun"
    "Samurai"
    "Kami"
    "Raiju"
    "Yokai"
    "Yurei"
    "Ninja"
    "Ronin"
    "Bushi"
    "Geinōjin"
    "Kensei"
    "Mythos"
    "Kamikaze"
    "Tengu"
    "Kodama"
    "Kaiju"
    "Bakemono"
    "Kappa"
    "Buddha"
    "Dharma"
    "Zazen"
    "Satori"
    "Karma"
    "Nirvana"
    "Meditation"
    "Zenith"
    "Samsara"
    "Enlightenment"
    "Satori"
    "Kensho"
"Zazen"
"Satori"
"Moksha"
"Enlightenment"
"Samadhi"
"Dharma"
"Koan"
"Zendo"
"Tathata"
"Shunyata"
"Bodhi"
"Zuihitsu"
"Shikantaza"
"Hua Tou"
"Mu"
"Zabuton"
"Zafu"
"Shojin"
"Tenzo"
"Rinzai"
"Soto"
"Yoga"
"Mindfulness"
"Compassion"
"Emptiness"
"Stillness"
"Harmony"
"Equanimity"
"Enlightenment"
"Karma"
"Samsara"
"Lotus"
"Dharma"
"Nirvana"
"Koan"
"Zazen"
"Bodhisattva"
"Mudra"
"Metta"
"Arhat"
"Sutra"
"Zenith"
"Sangha"
"Tantra"
"Buddha"
"Vajra"
"Tathagata"
"Amitabha"
"Mahayana"
"Theravada"
"Mantra"
"Anatta"
"Pure Land"
"Shingon"
"Tendai"
"Shinto"
"Kami"
"Amaterasu"
"Susano-o"
"Izanami"
"Izanagi"
"Yomi"
"Kagutsuchi"
"Raijin"
"Fujin"
"Kuebiko"
"Suijin"
"Kami-no-michi"
"Miko"
"Hachiman"
"Benzaiten"
"Fudō Myō-ō"
"Jizō"
"Kannon"
"Yakushi"
"Daikokuten"
"Ebisu"
"Jōdo Shinshū"
"Nichiren"
"Shinran"
"Taoism"
"Confucianism"
"Shugendo"
)

while true; do
    # Generate random nickname
    adjective=${adjectives[$RANDOM % ${#adjectives[@]} ]}
    noun=${nouns[$RANDOM % ${#nouns[@]} ]}
    nickname="${adjective}${noun}"

    # Output nickname in random color. 
    echo -e "\033[0;$(($RANDOM % 7 + 31))m${nickname}\033[0m"
            #echo -e "\033[0;$(($RANDOM % 7 + 31))m${adj^}${noun^}\033[0m"


    # Ask user if they like the nickname
    read -p "Do you like your new nickname? (y/n) " answer
    if [[ $answer == "y" ]]; then
        echo "Sayōnara! Arrivederci! ¡Adiós! До побачення! "
        exit 0
    fi
done
